name: Build binaries

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install nuitka
      - run: pip install getch
      - run: nuitka --onefile --standalone --include-package=getch game.py
      - uses: actions/upload-artifact@v4
        with:
          name: game-linux
          path: game.bin

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install nuitka pefile
      - run: python -m nuitka --onefile --standalone --windows-dependency-tool=pefile game.py
      - uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: game.exe
